First load the desired seasons of player data.

In [2]:
import pandas as pd
import os

# --- Configuration ---
DATA_DIR = '../data_collection/player_data_csvs'

# Using 2013-2023 for training to predict for 2024.
SEASONS_TO_LOAD = range(2013, 2024)


# --- Data Loading ---
all_season_dfs = []
print(f"Looking for data in: {os.path.abspath(DATA_DIR)}")

for season in SEASONS_TO_LOAD:
    file_path = os.path.join(DATA_DIR, f'fantasy_{season}.csv')
    
    if os.path.exists(file_path):
        print(f"Loading data for {season} season...")
        try:
            season_df = pd.read_csv(file_path)
            season_df['Season'] = season # Add a 'Season' column to identify the year for each row ( we are adding all seasons to the same dataframe)
            all_season_dfs.append(season_df)
        except Exception as e:
            print(f"Error loading {file_path}: {e}")
    else:
        print(f"Warning: File not found for season {season} at {file_path}")

# --- Combine and Inspect ---
if all_season_dfs:
    master_df = pd.concat(all_season_dfs, ignore_index=True)
    
    print("\\nSuccessfully loaded and combined data.")
    print(f"Seasons loaded: {sorted(master_df['Season'].unique())}")
    print(f"Total rows: {len(master_df)}")
    
    print('\\n--- First 5 Rows ---')
    display(master_df.head()) # quick view for sanity check, check season is first season in the defined range (i.e. 2013)

    print('\\n--- Last 5 Rows ---')
    display(master_df.tail()) # second quick view for consistency, check season is last season in the defined range (i.e. 2023)
    
    print('\\n--- DataFrame Info ---')
    master_df.info() # check column names and data types
else:
    print("\\nError: No data was loaded. Check file paths and season range.")

Looking for data in: c:\Users\Tyler\Desktop\FFPredictionsV2\data_collection\player_data_csvs
Loading data for 2013 season...
Loading data for 2014 season...
Loading data for 2015 season...
Loading data for 2016 season...
Loading data for 2017 season...
Loading data for 2018 season...
Loading data for 2019 season...
Loading data for 2020 season...
Loading data for 2021 season...
Loading data for 2022 season...
Loading data for 2023 season...
\nSuccessfully loaded and combined data.
Seasons loaded: [np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023)]
Total rows: 6847
\n--- First 5 Rows ---

,rank,player,team,position,age,games,games_started,completions,pass_attempts,pass_yards,...,two_point_conv_passes,standard_fantasy_points,ppr_fantasy_points,draftkings_points,fanduel_points,vbd,pos_rank,overall_rank,player_id,Season
0,1,Jamaal Charles,KAN,RB,27,15,15.0,0.0,0.0,0.0,...,NaN,308.0,378.0,386.0,343.0,182.0,1,1.0,CharJa00,2013
1,2,LeSean McCoy,PHI,RB,25,16,16.0,0.0,0.0,0.0,...,NaN,279.0,330.6,337.6,304.6,152.0,2,2.0,McCoLe01,2013
2,3,Peyton Manning,DEN,QB,37,16,16.0,450.0,659.0,5477.0,...,NaN,410.0,410.0,429.0,420.0,151.0,1,3.0,MannPe00,2013
3,4,Matt Forte,CHI,RB,28,16,16.0,0.0,0.0,0.0,...,NaN,263.0,337.3,345.3,300.3,137.0,3,4.0,FortMa00,2013
4,5,Jimmy Graham,NOR,TE,27,16,12.0,0.0,0.0,0.0,...,NaN,218.0,303.5,306.5,260.5,124.0,1,5.0,GrahJi00,2013

\n--- Last 5 Rows ---

,rank,player,team,position,age,games,games_started,completions,pass_attempts,pass_yards,...,two_point_conv_passes,standard_fantasy_points,ppr_fantasy_points,draftkings_points,fanduel_points,vbd,pos_rank,overall_rank,player_id,Season
6842,628,Kyle Allen,BUF,QB,27,7,0.0,0.0,0.0,0.0,...,NaN,-1.0,-1.3,-1.3,-1.3,NaN,83,NaN,AlleKy00,2023
6843,629,Deon Jackson,3TM,RB,24,4,1.0,0.0,0.0,0.0,...,NaN,-1.0,4.0,6.0,1.5,NaN,166,NaN,JackDe02,2023
6844,630,David Wells,TAM,TE,28,5,0.0,0.0,0.0,0.0,...,NaN,-1.0,1.0,1.0,NaN,NaN,140,NaN,WellDa00,2023
6845,631,James Proche,CLE,WR,27,10,1.0,0.0,0.0,0.0,...,NaN,-2.0,-2.0,-1.0,-2.0,NaN,242,NaN,ProcJa00,2023
6846,632,Trent Taylor,CHI,WR,29,17,0.0,0.0,0.0,0.0,...,NaN,-2.0,-2.2,-1.2,-2.2,NaN,243,NaN,TaylTr02,2023

\n--- DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6847 entries, 0 to 6846
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rank                     6847 non-null   int64
 1   player                   6847 non-null   object
 2   team                     6847 non-null   object
 3   position                 6847 non-null   object
 4   age                      6847 non-null   int64
 5   games                    6847 non-null   int64
 6   games_started            6835 non-null   float64
 7   completions              6845 non-null   float64
 8   pass_attempts            6845 non-null   float64
 9   pass_yards               6845 non-null   float64
 10  pass_tds                 6845 non-null   float64
 11  ints                     6845 non-null   float64
 12  rush_attempts            6845 non-null   float64
 13  rush_yards               6845 non-null   float64
 14  yards_per_rush_attempt   3551 non-null   float64
 15  rush_tds                 6845 non-null   float64
 16  targets                  6754 non-null   float64
 17  receptions               6845 non-null   float64
 18  rec_yds                  6845 non-null   float64
 19  yards_per_rec            5152 non-null   float64
 20  rec_tds                  6845 non-null   float64
 21  fumbles                  6477 non-null   float64
 22  fumbles_lost             6779 non-null   float64
 23  rush_and_rec_td_total    6847 non-null   int64
 24  two_point_convs_made     508 non-null    float64
 25  two_point_conv_passes    247 non-null    float64
 26  standard_fantasy_points  5962 non-null   float64
 27  ppr_fantasy_points       6101 non-null   float64
 28  draftkings_points        6098 non-null   float64
 29  fanduel_points           6096 non-null   float64
 30  vbd                      812 non-null    float64
 31  pos_rank                 6847 non-null   int64
 32  overall_rank             858 non-null    float64
 33  player_id                6847 non-null   object
 34  Season                   6847 non-null   int64
dtypes: float64(25), int64(6), object(4)
memory usage: 1.8+ MB

Quick check of the column names

In [3]:
print(master_df.columns.tolist())

['rank', 'player', 'team', 'position', 'age', 'games', 'games_started', 'completions', 'pass_attempts', 'pass_yards', 'pass_tds', 'ints', 'rush_attempts', 'rush_yards', 'yards_per_rush_attempt', 'rush_tds', 'targets', 'receptions', 'rec_yds', 'yards_per_rec', 'rec_tds', 'fumbles', 'fumbles_lost', 'rush_and_rec_td_total', 'two_point_convs_made', 'two_point_conv_passes', 'standard_fantasy_points', 'ppr_fantasy_points', 'draftkings_points', 'fanduel_points', 'vbd', 'pos_rank', 'overall_rank', 'player_id', 'Season']

Now clean the data. Need to remove NaNs and non-numerics like symbols. 
NaNs will be converted to 0s as this typically means a player did not record any activity in this category.

In [4]:
# This code assumes 'master_df' exists from the previous cell.
import numpy as np

# --- Data Cleaning and Type Conversion ---

# 1. Clean Player Names
# Remove special characters like '*' (Pro-Bowl) and '+' (All-Pro) for consistent naming.
if 'player' in master_df.columns:
    master_df['player'] = master_df['player'].str.replace(r'[\\*\\+]', '', regex=True).str.strip()
    print("Cleaned player names.")

# 2. Identify Column Types
ID_COLS = ['player', 'team', 'position', 'player_id'] # text or identifier cols, all others are numeric
NUMERIC_COLS = [col for col in master_df.columns if col not in ID_COLS]

# 3. Convert Columns to Numeric and Handle Missing Values
# Coerce errors, turning any non-numeric value into NaN, then fill with 0.
master_df[NUMERIC_COLS] = master_df[NUMERIC_COLS].apply(pd.to_numeric, errors='coerce').fillna(0)
print(f"Converted {len(NUMERIC_COLS)} columns to numeric and filled NaNs with 0.")

# 4. Convert float columns that should be integers to int type
# These are columns representing counts, ranks, or whole numbers.
INT_COLS = [
    'rank', 'age', 'games', 'games_started', 'completions', 'pass_attempts', 
    'pass_yards', 'pass_tds', 'ints', 'rush_attempts', 'rush_yards', 'rush_tds',
    'targets', 'receptions', 'rec_yds', 'rec_tds', 'fumbles', 'fumbles_lost',
    'rush_and_rec_td_total', 'two_point_convs_made', 'two_point_conv_passes',
    'vbd', 'pos_rank', 'overall_rank', 'Season'
]
# Convert columns that actually exist in the DataFrame
existing_int_cols = [col for col in INT_COLS if col in master_df.columns]
master_df[existing_int_cols] = master_df[existing_int_cols].astype(np.int64)
print(f"Converted {len(existing_int_cols)} columns to integer type.")

# --- Verification ---
print("\\n--- DataFrame Info After Cleaning ---")
master_df.info()

print("\\n--- Sample of Cleaned Data ---")
# display(master_df.head())
print(master_df.head())

Cleaned player names.
Converted 31 columns to numeric and filled NaNs with 0.
Converted 25 columns to integer type.
\n--- DataFrame Info After Cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6847 entries, 0 to 6846
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rank                     6847 non-null   int64
 1   player                   6847 non-null   object
 2   team                     6847 non-null   object
 3   position                 6847 non-null   object
 4   age                      6847 non-null   int64
 5   games                    6847 non-null   int64
 6   games_started            6847 non-null   int64
 7   completions              6847 non-null   int64
 8   pass_attempts            6847 non-null   int64
 9   pass_yards               6847 non-null   int64
 10  pass_tds                 6847 non-null   int64
 11  ints                     6847 non-null   int64
 12  rush_attempts            6847 non-null   int64
 13  rush_yards               6847 non-null   int64
 14  yards_per_rush_attempt   6847 non-null   float64
 15  rush_tds                 6847 non-null   int64
 16  targets                  6847 non-null   int64
 17  receptions               6847 non-null   int64
 18  rec_yds                  6847 non-null   int64
 19  yards_per_rec            6847 non-null   float64
 20  rec_tds                  6847 non-null   int64
 21  fumbles                  6847 non-null   int64
 22  fumbles_lost             6847 non-null   int64
 23  rush_and_rec_td_total    6847 non-null   int64
 24  two_point_convs_made     6847 non-null   int64
 25  two_point_conv_passes    6847 non-null   int64
 26  standard_fantasy_points  6847 non-null   float64
 27  ppr_fantasy_points       6847 non-null   float64
 28  draftkings_points        6847 non-null   float64
 29  fanduel_points           6847 non-null   float64
 30  vbd                      6847 non-null   int64
 31  pos_rank                 6847 non-null   int64
 32  overall_rank             6847 non-null   int64
 33  player_id                6847 non-null   object
 34  Season                   6847 non-null   int64
dtypes: float64(6), int64(25), object(4)
memory usage: 1.8+ MB
\n--- Sample of Cleaned Data ---
   rank          player team position  age  games  games_started  completions  \
0     1  Jamaal Charles  KAN       RB   27     15             15            0
1     2    LeSean McCoy  PHI       RB   25     16             16            0
2     3  Peyton Manning  DEN       QB   37     16             16          450
3     4      Matt Forte  CHI       RB   28     16             16            0
4     5    Jimmy Graham  NOR       TE   27     16             12            0

   pass_attempts  pass_yards  ...  two_point_conv_passes  \
0              0           0  ...                      0
1              0           0  ...                      0
2            659        5477  ...                      0
3              0           0  ...                      0
4              0           0  ...                      0

   standard_fantasy_points  ppr_fantasy_points  draftkings_points  \
0                    308.0               378.0              386.0
1                    279.0               330.6              337.6
2                    410.0               410.0              429.0
3                    263.0               337.3              345.3
4                    218.0               303.5              306.5

   fanduel_points  vbd  pos_rank  overall_rank  player_id  Season
0           343.0  182         1             1   CharJa00    2013
1           304.6  152         2             2   McCoLe01    2013
2           420.0  151         1             3   MannPe00    2013
3           300.3  137         3             4   FortMa00    2013
4           260.5  124         1             5   GrahJi00    2013

[5 rows x 35 columns]

Feature engineering next

In [ ]:
# This code assumes 'master_df' exists and is cleaned from the previous cells.
import pandas as pd
import numpy as np

# --- Configuration ---
N_LAG_SEASONS = 3 # Set to 3 for now to keep feature count manageable, but can be increased

STATS_TO_LAG = [
    'age', 'games', 'games_started', 'completions', 'pass_attempts', 
    'pass_yards', 'pass_tds', 'ints', 'rush_attempts', 'rush_yards', 
    'yards_per_rush_attempt', 'rush_tds', 'targets', 'receptions', 'rec_yds', 
    'yards_per_rec', 'rec_tds', 'fumbles', 'fumbles_lost',
    'ppr_fantasy_points'
]
TARGET_VARIABLE = 'ppr_fantasy_points'

# --- Feature Engineering (Enhanced) ---
print("Starting ENHANCED feature engineering...")
master_df = master_df.sort_values(by=['player_id', 'Season'])
all_features = []
grouped = master_df.groupby('player_id')

for player_id, player_df in grouped:
    for i in range(1, len(player_df)):
        target_season_data = player_df.iloc[i]
        
        features = {
            'player_id': player_id,
            'player_name': target_season_data['player'],
            'position': target_season_data['position'],
            'prediction_season': int(target_season_data['Season']),
            'target_ppr_points': target_season_data[TARGET_VARIABLE]
        }

        # Step 1: Create basic lagged features (S-1, S-2, etc.)
        for lag in range(1, N_LAG_SEASONS + 1):
            if i - lag >= 0:
                past_season = player_df.iloc[i - lag]
                for stat in STATS_TO_LAG:
                    features[f'{stat}_s_minus_{lag}'] = past_season[stat]
            else:
                for stat in STATS_TO_LAG:
                    features[f'{stat}_s_minus_{lag}'] = 0
        
        # Step 2: Create Derived Features (Averages, Trends, etc)
        # --- Per-Game & Efficiency Metrics ---
        for lag in range(1, N_LAG_SEASONS + 1):
            games_played = features.get(f'games_s_minus_{lag}', 0)
            if games_played > 0:
                features[f'ppr_per_game_s_minus_{lag}'] = features[f'ppr_fantasy_points_s_minus_{lag}'] / games_played
                features[f'rush_yards_per_game_s_minus_{lag}'] = features[f'rush_yards_s_minus_{lag}'] / games_played
                features[f'rec_yards_per_game_s_minus_{lag}'] = features[f'rec_yds_s_minus_{lag}'] / games_played
                features[f'pass_yards_per_game_s_minus_{lag}'] = features[f'pass_yards_s_minus_{lag}'] / games_played
            else:
                features[f'ppr_per_game_s_minus_{lag}'] = 0
                features[f'rush_yards_per_game_s_minus_{lag}'] = 0
                features[f'rec_yards_per_game_s_minus_{lag}'] = 0
                features[f'pass_yards_per_game_s_minus_{lag}'] = 0

        # --- Multi-Season Aggregates & Volatility ---
        # Last 2 Seasons
        last_2_seasons_points = [features.get(f'ppr_fantasy_points_s_minus_{j}', 0) for j in range(1, 3)]
        valid_points_l2 = [p for p in last_2_seasons_points if p > 0]
        if valid_points_l2:
            features['avg_ppr_last_2_seasons'] = np.mean(valid_points_l2)
        else:
            features['avg_ppr_last_2_seasons'] = 0
            
        # Last 3 Seasons
        last_3_seasons_points = [features.get(f'ppr_fantasy_points_s_minus_{j}', 0) for j in range(1, 4)]
        valid_points_l3 = [p for p in last_3_seasons_points if p > 0]
        if valid_points_l3:
            features['avg_ppr_last_3_seasons'] = np.mean(valid_points_l3)
            features['std_dev_ppr_last_3_seasons'] = np.std(valid_points_l3)
        else:
            features['avg_ppr_last_3_seasons'] = 0
            features['std_dev_ppr_last_3_seasons'] = 0

        # --- Year-over-Year Trends ---
        s1_points = features.get('ppr_fantasy_points_s_minus_1', 0)
        s2_points = features.get('ppr_fantasy_points_s_minus_2', 0)
        if s1_points > 0 and s2_points > 0:
            features['ppr_trend_s1_vs_s2'] = s1_points - s2_points
        else:
            features['ppr_trend_s1_vs_s2'] = 0
            
        all_features.append(features)

# --- Create Final Training DataFrame ---
if all_features:
    training_df = pd.DataFrame(all_features).fillna(0) # again, fill any last missing values with 0
    
    print("\\nSuccessfully created the training DataFrame with ENHANCED features.")
    print('\\n--- Training DataFrame Info ---')
    training_df.info()
    
    print('\\n--- Sample of Training Data Columns ---')
    print(training_df.columns.tolist())

    print('\\n--- Example: Feature set for Christian McCaffrey (a player with volatility) ---')
    # display(training_df[training_df['player_name'] == 'Christian McCaffrey'])
    print(training_df[training_df['player_name'] == 'Christian McCaffrey'])
else:
    print("\\nError: No features were generated.")

Starting ENHANCED feature engineering...
\nSuccessfully created the training DataFrame with ENHANCED features.
\n--- Training DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4841 entries, 0 to 4840
Columns: 249 entries, player_id to ppr_trend_s1_vs_s2
dtypes: float64(75), int64(171), object(3)
memory usage: 9.2+ MB
\n--- Sample of Training Data Columns ---
['player_id', 'player_name', 'position', 'prediction_season', 'target_ppr_points', 'age_s_minus_1', 'games_s_minus_1', 'games_started_s_minus_1', 'completions_s_minus_1', 'pass_attempts_s_minus_1', 'pass_yards_s_minus_1', 'pass_tds_s_minus_1', 'ints_s_minus_1', 'rush_attempts_s_minus_1', 'rush_yards_s_minus_1', 'yards_per_rush_attempt_s_minus_1', 'rush_tds_s_minus_1', 'targets_s_minus_1', 'receptions_s_minus_1', 'rec_yds_s_minus_1', 'yards_per_rec_s_minus_1', 'rec_tds_s_minus_1', 'fumbles_s_minus_1', 'fumbles_lost_s_minus_1', 'ppr_fantasy_points_s_minus_1', 'age_s_minus_2', 'games_s_minus_2', 'games_started_s_minus_2', 'completions_s_minus_2', 'pass_attempts_s_minus_2', 'pass_yards_s_minus_2', 'pass_tds_s_minus_2', 'ints_s_minus_2', 'rush_attempts_s_minus_2', 'rush_yards_s_minus_2', 'yards_per_rush_attempt_s_minus_2', 'rush_tds_s_minus_2', 'targets_s_minus_2', 'receptions_s_minus_2', 'rec_yds_s_minus_2', 'yards_per_rec_s_minus_2', 'rec_tds_s_minus_2', 'fumbles_s_minus_2', 'fumbles_lost_s_minus_2', 'ppr_fantasy_points_s_minus_2', 'age_s_minus_3', 'games_s_minus_3', 'games_started_s_minus_3', 'completions_s_minus_3', 'pass_attempts_s_minus_3', 'pass_yards_s_minus_3', 'pass_tds_s_minus_3', 'ints_s_minus_3', 'rush_attempts_s_minus_3', 'rush_yards_s_minus_3', 'yards_per_rush_attempt_s_minus_3', 'rush_tds_s_minus_3', 'targets_s_minus_3', 'receptions_s_minus_3', 'rec_yds_s_minus_3', 'yards_per_rec_s_minus_3', 'rec_tds_s_minus_3', 'fumbles_s_minus_3', 'fumbles_lost_s_minus_3', 'ppr_fantasy_points_s_minus_3', 'age_s_minus_4', 'games_s_minus_4', 'games_started_s_minus_4', 'completions_s_minus_4', 'pass_attempts_s_minus_4', 'pass_yards_s_minus_4', 'pass_tds_s_minus_4', 'ints_s_minus_4', 'rush_attempts_s_minus_4', 'rush_yards_s_minus_4', 'yards_per_rush_attempt_s_minus_4', 'rush_tds_s_minus_4', 'targets_s_minus_4', 'receptions_s_minus_4', 'rec_yds_s_minus_4', 'yards_per_rec_s_minus_4', 'rec_tds_s_minus_4', 'fumbles_s_minus_4', 'fumbles_lost_s_minus_4', 'ppr_fantasy_points_s_minus_4', 'age_s_minus_5', 'games_s_minus_5', 'games_started_s_minus_5', 'completions_s_minus_5', 'pass_attempts_s_minus_5', 'pass_yards_s_minus_5', 'pass_tds_s_minus_5', 'ints_s_minus_5', 'rush_attempts_s_minus_5', 'rush_yards_s_minus_5', 'yards_per_rush_attempt_s_minus_5', 'rush_tds_s_minus_5', 'targets_s_minus_5', 'receptions_s_minus_5', 'rec_yds_s_minus_5', 'yards_per_rec_s_minus_5', 'rec_tds_s_minus_5', 'fumbles_s_minus_5', 'fumbles_lost_s_minus_5', 'ppr_fantasy_points_s_minus_5', 'age_s_minus_6', 'games_s_minus_6', 'games_started_s_minus_6', 'completions_s_minus_6', 'pass_attempts_s_minus_6', 'pass_yards_s_minus_6', 'pass_tds_s_minus_6', 'ints_s_minus_6', 'rush_attempts_s_minus_6', 'rush_yards_s_minus_6', 'yards_per_rush_attempt_s_minus_6', 'rush_tds_s_minus_6', 'targets_s_minus_6', 'receptions_s_minus_6', 'rec_yds_s_minus_6', 'yards_per_rec_s_minus_6', 'rec_tds_s_minus_6', 'fumbles_s_minus_6', 'fumbles_lost_s_minus_6', 'ppr_fantasy_points_s_minus_6', 'age_s_minus_7', 'games_s_minus_7', 'games_started_s_minus_7', 'completions_s_minus_7', 'pass_attempts_s_minus_7', 'pass_yards_s_minus_7', 'pass_tds_s_minus_7', 'ints_s_minus_7', 'rush_attempts_s_minus_7', 'rush_yards_s_minus_7', 'yards_per_rush_attempt_s_minus_7', 'rush_tds_s_minus_7', 'targets_s_minus_7', 'receptions_s_minus_7', 'rec_yds_s_minus_7', 'yards_per_rec_s_minus_7', 'rec_tds_s_minus_7', 'fumbles_s_minus_7', 'fumbles_lost_s_minus_7', 'ppr_fantasy_points_s_minus_7', 'age_s_minus_8', 'games_s_minus_8', 'games_started_s_minus_8', 'completions_s_minus_8', 'pass_attempts_s_minus_8', 'pass_yards_s_minus_8', 'pass_tds_s_minus_8', 'ints_s_minus_8', 'rush_attempts_s_minus_8', 'rush_yards_s_minus_8', 'yards_per_rush_attempt_s_minus_8', 'rush_tds_s_minus_8', 'targets_s_minus_8', 'receptions_s_minus_8', 'rec_yds_s_minus_8', 'yards_per_rec_s_minus_8', 'rec_tds_s_minus_8', 'fumbles_s_minus_8', 'fumbles_lost_s_minus_8', 'ppr_fantasy_points_s_minus_8', 'age_s_minus_9', 'games_s_minus_9', 'games_started_s_minus_9', 'completions_s_minus_9', 'pass_attempts_s_minus_9', 'pass_yards_s_minus_9', 'pass_tds_s_minus_9', 'ints_s_minus_9', 'rush_attempts_s_minus_9', 'rush_yards_s_minus_9', 'yards_per_rush_attempt_s_minus_9', 'rush_tds_s_minus_9', 'targets_s_minus_9', 'receptions_s_minus_9', 'rec_yds_s_minus_9', 'yards_per_rec_s_minus_9', 'rec_tds_s_minus_9', 'fumbles_s_minus_9', 'fumbles_lost_s_minus_9', 'ppr_fantasy_points_s_minus_9', 'age_s_minus_10', 'games_s_minus_10', 'games_started_s_minus_10', 'completions_s_minus_10', 'pass_attempts_s_minus_10', 'pass_yards_s_minus_10', 'pass_tds_s_minus_10', 'ints_s_minus_10', 'rush_attempts_s_minus_10', 'rush_yards_s_minus_10', 'yards_per_rush_attempt_s_minus_10', 'rush_tds_s_minus_10', 'targets_s_minus_10', 'receptions_s_minus_10', 'rec_yds_s_minus_10', 'yards_per_rec_s_minus_10', 'rec_tds_s_minus_10', 'fumbles_s_minus_10', 'fumbles_lost_s_minus_10', 'ppr_fantasy_points_s_minus_10', 'ppr_per_game_s_minus_1', 'rush_yards_per_game_s_minus_1', 'rec_yards_per_game_s_minus_1', 'pass_yards_per_game_s_minus_1', 'ppr_per_game_s_minus_2', 'rush_yards_per_game_s_minus_2', 'rec_yards_per_game_s_minus_2', 'pass_yards_per_game_s_minus_2', 'ppr_per_game_s_minus_3', 'rush_yards_per_game_s_minus_3', 'rec_yards_per_game_s_minus_3', 'pass_yards_per_game_s_minus_3', 'ppr_per_game_s_minus_4', 'rush_yards_per_game_s_minus_4', 'rec_yards_per_game_s_minus_4', 'pass_yards_per_game_s_minus_4', 'ppr_per_game_s_minus_5', 'rush_yards_per_game_s_minus_5', 'rec_yards_per_game_s_minus_5', 'pass_yards_per_game_s_minus_5', 'ppr_per_game_s_minus_6', 'rush_yards_per_game_s_minus_6', 'rec_yards_per_game_s_minus_6', 'pass_yards_per_game_s_minus_6', 'ppr_per_game_s_minus_7', 'rush_yards_per_game_s_minus_7', 'rec_yards_per_game_s_minus_7', 'pass_yards_per_game_s_minus_7', 'ppr_per_game_s_minus_8', 'rush_yards_per_game_s_minus_8', 'rec_yards_per_game_s_minus_8', 'pass_yards_per_game_s_minus_8', 'ppr_per_game_s_minus_9', 'rush_yards_per_game_s_minus_9', 'rec_yards_per_game_s_minus_9', 'pass_yards_per_game_s_minus_9', 'ppr_per_game_s_minus_10', 'rush_yards_per_game_s_minus_10', 'rec_yards_per_game_s_minus_10', 'pass_yards_per_game_s_minus_10', 'avg_ppr_last_2_seasons', 'avg_ppr_last_3_seasons', 'std_dev_ppr_last_3_seasons', 'ppr_trend_s1_vs_s2']
\n--- Example: Feature set for Christian McCaffrey (a player with volatility) ---
     player_id          player_name position  prediction_season  \
2831  McCaCh01  Christian McCaffrey       RB               2018
2832  McCaCh01  Christian McCaffrey       RB               2019
2833  McCaCh01  Christian McCaffrey       RB               2020
2834  McCaCh01  Christian McCaffrey       RB               2021
2835  McCaCh01  Christian McCaffrey       RB               2022
2836  McCaCh01  Christian McCaffrey       RB               2023

      target_ppr_points  age_s_minus_1  games_s_minus_1  \
2831              385.5             21               16
2832              471.2             22               16
2833               90.4             23               16
2834              127.5             24                3
2835              356.4             25                7
2836              391.3             26               17

      games_started_s_minus_1  completions_s_minus_1  pass_attempts_s_minus_1  \
2831                       10                      0                        0
2832                       16                      1                        1
2833                       16                      0                        2
2834                        3                      0                        0
2835                        7                      0                        0
2836                       16                      1                        1

      ...  rec_yards_per_game_s_minus_9  pass_yards_per_game_s_minus_9  \
2831  ...                           0.0                            0.0
2832  ...                           0.0                            0.0
2833  ...                           0.0                            0.0
2834  ...                           0.0                            0.0
2835  ...                           0.0                            0.0
2836  ...                           0.0                            0.0

      ppr_per_game_s_minus_10  rush_yards_per_game_s_minus_10  \
2831                      0.0                             0.0
2832                      0.0                             0.0
2833                      0.0                             0.0
2834                      0.0                             0.0
2835                      0.0                             0.0
2836                      0.0                             0.0

      rec_yards_per_game_s_minus_10  pass_yards_per_game_s_minus_10  \
2831                            0.0                             0.0
2832                            0.0                             0.0
2833                            0.0                             0.0
2834                            0.0                             0.0
2835                            0.0                             0.0
2836                            0.0                             0.0

      avg_ppr_last_2_seasons  avg_ppr_last_3_seasons  \
2831                  228.60              228.600000
2832                  307.05              307.050000
2833                  428.35              361.766667
2834                  280.80              315.700000
2835                  108.95              229.700000
2836                  241.95              191.433333

      std_dev_ppr_last_3_seasons  ppr_trend_s1_vs_s2
2831                    0.000000                 0.0
2832                   78.450000               156.9
2833                  100.452786                85.7
2834                  163.107715              -380.8
2835                  171.436655                37.1
2836                  117.628237               228.9

[6 rows x 249 columns]

Now Train the Model. GradientBoost.

In [8]:
# This code assumes 'training_df' exists from the previous cell.
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import joblib
import os
import pandas as pd

# --- Model Preparation ---

# 1. Separate Features (X) from Target (y)
# Drop non-predictive ID columns and the target variable itself from the feature set.
FEATURES_TO_DROP = ['player_id', 'player_name', 'prediction_season', 'target_ppr_points']
X = training_df.drop(columns=FEATURES_TO_DROP)
y = training_df['target_ppr_points']

# 2. Handle Categorical Features (One-Hot Encoding)
# 'position' is a text column. Convert it into numerical format so the model can use it.
# 'pd.get_dummies' creates a new binary column for each unique position (e.g., 'position_QB', 'position_RB').
X = pd.get_dummies(X, columns=['position'], prefix='pos', drop_first=True)

# 3. Split Data into Training and Testing Sets
# Use data from seasons before 2023 to train the model, and the 2023 season data to test it.
# This chronological split mimics the real-world use case of predicting a future season.
X_train = X[training_df['prediction_season'] < 2023]
y_train = y[training_df['prediction_season'] < 2023]
X_test = X[training_df['prediction_season'] == 2023]
y_test = y[training_df['prediction_season'] == 2023]

print("Data split into training and testing sets:")
print(f"  Training samples: {len(X_train)}")
print(f"  Testing samples:  {len(X_test)}")


# --- Model Training ---
print("\nTraining the Gradient Boosting Regressor model...")

# Initialize the model with some robust starting parameters.
# n_estimators: number of boosting stages to be run.
# max_depth: maximum depth of the individual regression estimators.
# learning_rate: shrinks the contribution of each tree.
# subsample: fraction of samples to be used for fitting the individual base learners.
# random_state: for reproducibility.
gbr = GradientBoostingRegressor(
    n_estimators=500, 
    max_depth=5, 
    learning_rate=0.05, 
    subsample=0.8,
    random_state=42
)

# Train the model on the training data
gbr.fit(X_train, y_train)

print("Model training complete.")


# --- Model Evaluation ---
print("\nEvaluating model performance on the unseen 2023 test set...")

test_predictions = gbr.predict(X_test)
mae = mean_absolute_error(y_test, test_predictions)
r2 = r2_score(y_test, test_predictions)

print(f"  Mean Absolute Error (MAE): {mae:.2f}")
print(f"  R-squared (R²): {r2:.3f}")
print("\n(MAE - on average, how many fantasy points the prediction was off by)")
print("(R² - what percentage of the variance in the target variable the model explains)")


# --- Save the Trained Model ---
# save the trained model to easily load and use it later for 2024 predictions
MODEL_DIR = '../modeling/'
if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR)

model_filename = os.path.join(MODEL_DIR, 'fantasy_football_predictor.joblib')
joblib.dump(gbr, model_filename)

print(f"\nModel saved to: {os.path.abspath(model_filename)}")

Data split into training and testing sets:
  Training samples: 4335
  Testing samples:  506

Training the Gradient Boosting Regressor model...
Model training complete.

Evaluating model performance on the unseen 2023 test set...
  Mean Absolute Error (MAE): 41.53
  R-squared (R²): 0.546

(MAE - on average, how many fantasy points the prediction was off by)
(R² - what percentage of the variance in the target variable the model explains)

Model saved to: c:\Users\Tyler\Desktop\FFPredictionsV2\modeling\fantasy_football_predictor.joblib